### ISSUE TITLE
Implement not acked status

### ISSUE THREAD

**Issue by aleksandrzhiliaev** [urbanindo/yii2-queue#52] opened 2017-01-12 20:42 UTC
I wanted to go through all queue, for now I can't do it without acking messages..
For example I have 3 jobs but when I running `listen` I always see first job:
```
Running new process...
Running job #: 7

Running new process...
Running job #: 7

Running new process...
Running job #: 7
...
```

So if we can add smth: `$this->notAck();` then it will be like:
```
Running new process...
Running job #: 7
Not acked! Skipping..

Running new process...
Running job #: 6
Not acked! Skipping..

Running new process...
Running job #: 5
Not acked! Skipping..

```

And all unacked jobs will be in queue

**Comment by petrabarus** [comment] 2017-01-13 01:25
I don't understand.

What happens with the job when you not ack it? Will it go back to the queue or will it be deleted?

**Comment by Sassoft** [comment] 2017-01-13 08:52
If you don't ack message the job will be in queue and you will run next job..
Now the problem is that I can't go to the next job #2 if I don't want to ack job #1. It always be job #1 in queue.

**Comment by Sassoft** [comment] 2017-01-13 08:54
Example in rabbitmq: https://www.rabbitmq.com/tutorials/tutorial-two-python.html
```
Forgotten acknowledgment

It's a common mistake to miss the basic_ack. It's an easy error, but the consequences are serious.
Messages will be redelivered when your client quits (which may look like random redelivery), but RabbitMQ will eat more and more memory as it won't be able to release any unacked messages.
```

**Closed** 2018-05-06 14:07 UTC
